# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Demo
    
    pod 'Kingfisher', '~> 3.0'
    pod 'Alamofire', '~> 4.0'
    pod 'AlamofireObjectMapper', '~> 4.0'
    pod 'SVProgressHUD'
end
